name: MCN
version: $version
description: Snadné sdílení a analýza logů serveru
author: Fejby
website: https://log.mcnavody.eu/

main: gs.mclo.bukkit.MclogsPlugin
api-version: 1.13
folia-supported: true

commands:
  log:
    description: Nahrajte své logy na https://log.mcnavody.eu/
    usage: "/log <list | share> <soubor>"

permissions:
  mcn.*:
    description: Umožňuje přístup ke všem příkazům
    children:
      mcn.upload: true
      mcn.list: true
      mcn.share: true
  mcn.upload:
    description: Umožňuje nahrát aktuální soubor logu
    default: op
  mcn.list:
    description: Umožňuje vypsat dostupné soubory logů
    default: op
  mcn.share:
    description: Umožňuje sdílení konkrétních souborů logů
    default: op